# Where Next?

From what started as a half hour hack, and turned into a two week learning journey and write-up, which also included how to use `bookdown` to publish web-browseable books, as well as PDFs, from Rmd documents, this book provides something of a travelogue around the bye-ways of working with geographical route data.

Having been on the journey, several things occur to me. Firstly, if I ever need a present for a rally fan, I should be able to make a 3D model of their favourite stage or a custom map showing paths, trails and picnic spots around a woodland stage. Secondly, the idea of *stage route analysis* may be worth pursuing in terms of looking for profile stories *from the stage route* in advance of a rally, or perhaps to support a rally journalism write up of the events that transpired on a particular stage. I suspect I've only just started to touch on what the ecologists get up to with their path analysis, so this will likely reward further reading. Using stage route metrics to tag stages in terms of twistiness and elevation change, and use these as factors to see if they impact on driver performance, is another exciting possibility, using stage maps retrieved from [*rally-maps.com*](https://www.rally-maps.com/home) and results from [*ewrc-results.com*](https://www.ewrc-results.com/).

One thing I haven't really touched on is adding infographics to stage maps. Elsewhere, I have dabbled with various ways of visually reporting on stage times and pace maps over a rally (the split times for for WRC are still on hold as a I repair my data scrapers!)

Another thing that is missing from this book is the spatial analysis of collected or sampled data. I do have a stash of old WRC+ telemetry data somewhere, so a couple of half hour hacks (?!) immediately suggest themselves to me: firstly, revisiting the simple plots I originally made of them and finding ways of integrating them with some of the `leaflet` map views in particular; secondly, analysing their "group" behaviour to see how that unusual beast, the rally driver, behaves in general on a particular stage, and how and why other drivers perhaps stand out.

What's certain is that this isn't the end of the story. With this book now in the state it is, its something I can continue to update and to add to... The telemetry style analysis will probably be the focus of another project, however. If holidays are locked out again, that could well be how I spend my  summer holiday fortnight!